[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#11121D"
foreground = "#a9b1d6"

[font]
size = 10

[font.bold]
family = "SauceCodeProNerdFont"
style = "Bold"

[font.bold_italic]
family = "SauceCodeProNerdFont"
style = "Bold Italic"

[font.italic]
family = "SauceCodeProNerdFont"
style = "Italic"

[font.normal]
family = "SauceCodeProNerdFont"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.3

[window.padding]
x = 5
y = 5
