icons_format = "{icon}"

[theme]
theme = "solarized-dark"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
icons = "awesome4"
[icons.overrides]


[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "
format_alt = " $icon $frequency{ $boost|} "

[[block]]
block = "memory"
format = " $icon $mem_used "

format_alt = "$icon $mem_total.eng(w:1) total \uf205 "
# format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "sound"
# [block.mappings]
# "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__hw_sofhdadsp__sink" = "Speakers"
# "alsa_output.usb-0b0e_Jabra_Link_380_50C2ED793D95-00.analog-stereo" = "Headset"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "menu"
text = "\uf0c9 "
[[block.items]]
display = "Built In Speaker"
cmd = "~/scripts/speaker.sh"
[[block.items]]
display = "change primary"
cmd = "~/scripts/toggle_primary.sh"
[[block]]
block = "net"
format = " $icon {$signal_strength $ssid }"
[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%a %d/%m %R') "


# [[block]]
# block = "xrandr"
# format = " $icon $brightness $resolution "
# [[block]]
# block = "memory"
# format = " $icon $mem_total_used_percents.eng(w:2) "
# format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
# [[block]]
# block = "toggle"
# format = " $icon 4k "
# command_state = "xrandr | grep 'DP1 connected 38' | grep -v eDP1"
# command_on = "xrandr --output DVI-I-2-2 --mode 1920x1080 --rate 60.00 --primary"
# command_off = "xrandr --output eDP-1 --primary"
# interval = 5
